# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/micrograd-nbdev',
                'doc_host': 'https://Iamalos.github.io',
                'git_url': 'https://github.com/Iamalos/micrograd-nbdev',
                'lib_path': 'micrograd_nbdev'},
  'syms': {'micrograd_nbdev.engine': {'micrograd_nbdev.engine.say_hello': ('engine.html#say_hello', 'micrograd_nbdev/engine.py')}}}
